#!/bin/bash

#user-definable variables
STARTLINE='# generated by setup.sh (https://github.com/The-Pipeman-Organization/rosbot)'
ENDLINE='# end of ros-setup. DO NOT REMOVE COMMENTS!'
BASHRCLOCATION="${HOME}/.bashrc"
TEMPLOCATION="${HOME}/setup.tmp"

#colors!
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'


  while ! [ "$YNm" = "y" ]||[ "$YNm" = "Y" ]; do
  echo -e "\n${STARTLINE}" > $TEMPLOCATION
  printf "${YELLOW}Add workspace sourcing to ${BASHRCLOCATION}? (e.g.:source /root/catkin_ws/devel/setup.bash) y/n${NC}%s\n"
  read -r YN
  while [ "$YN" = "y" ]||[ "$YN" = "Y" ]; do
    printf "${YELLOW}enter setup bash name (e.g.:/root/catkin_ws/devel/setup.bash)${NC}%s\n"
    read -r FILE
      if [ -x $FILE ]; then
        echo "source" "${FILE}" >> $TEMPLOCATION
        printf "${GREEN}success${NC}%s\n"
      else
        if [ -e $FILE ]; then
          printf "${RED}ERROR: file ${FILE} not executable, probably lacking permissions, try chmod.${NC}%s\n"
          printf "${YELLOW}Chmod now? y/n${NC}%s\n"
          read -r YN
          if [ "$YN" = "y" ]||[ "$YN" = "Y" ]; then
              { chmod +x ${FILE}; }||{ printf "${RED}ERROR: could not chmod file, probably lacking permissions${FILE} ${NC}%s\n" && exit; }
              printf "${GREEN}success${NC}%s\n"
              echo "source" "${FILE}" >> $TEMPLOCATION
          fi
        else
          printf "${RED}ERROR: could not find file ${FILE} ${NC}%s\n"
        fi
      fi
    printf "${YELLOW}Add another workspace/retry? y/n${NC}%s\n"
    read -r YN
  done

  printf "${YELLOW}Add automatic IP configurating to ${BASHRCLOCATION}? y/n${NC}%s\n"
  read -r YN
  if [ "$YN" = "y" ]||[ "$YN" = "Y" ]; then
    printf "${YELLOW}Set up as Robot or Computer? r/c${NC}%s\n"
    read -r RC
    while ! { [ "$RC" = "r" ]||[ "$RC" = "R" ]||[ "$RC" = "c" ]||[ "$RC" = "C" ]; }; do
      printf "${RED}Invalid input\n${YELLOW}Set up as Robot or Computer? r/c${NC}%s\n"
      read -r RC
    done
    if [ "$RC" = "r" ]||[ "$RC" = "R" ]; then
      printf "${GREEN}Setting up as robot...${NC}%s\n\n"
        {
        echo -e "\nMYIP=\$(hostname -I | awk '{print \$1}')";
        echo "export ROS_MASTER_URI=http://\${MYIP}:11311";
        echo "export ROS_IP=\${MYIP}";
        echo "export ROS_HOSTNAME=\${MYIP}";
        } >> $TEMPLOCATION
    else
      printf "${YELLOW}Enter robot IP (a robot with a static IP really helps here): ${NC}%s\n"
      read -r IP
      printf "${GREEN}Setting up as computer, robot IP = ${IP}${NC}%s\n\n"
        {
        echo -e "\nMYIP=\$(hostname -I | awk '{print \$1}')";
        echo "export ROS_MASTER_URI=http://${IP}:11311";
        echo "export ROS_IP=\${MYIP}";
        echo "export ROS_HOSTNAME=\${MYIP}";
        } >> $TEMPLOCATION
    fi
  fi

  echo "${ENDLINE}" >> $TEMPLOCATION
  cat $TEMPLOCATION
  printf "${GREEN}\nDoes this look correct? y/n${NC}%s\n"
  read -r YNm
done

START=$(grep -nw "${STARTLINE}" "${BASHRCLOCATION}" | cut -f1 -d:)
END=$(grep -nw "${ENDLINE}" "${BASHRCLOCATION}" | cut -f1 -d:)

echo $START && echo "start"
echo $END && echo "end"

if [ -n "${END}" ]||[ -n "${START}" ]; then
  sed -i "${START},${END}d" "${BASHRCLOCATION}"
fi
cat $TEMPLOCATION >> $BASHRCLOCATION
rm $TEMPLOCATION

